name: CI

on:
    pull_request:

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    run_danger:
        name: Test on macOS
        runs-on: macOS-13
        strategy:
            fail-fast: false
            matrix:
                xcode: ["14.3.1"]
        steps:
            - uses: actions/checkout@v2

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      .build/artifacts
                      .build/checkouts
                      .build/repositories
                  key: ${{ runner.os }}-dependencies-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
                      ${{ runner.os }}-dependencies-${{ matrix.xcode }}-
            - name: Select Xcode
              run: |
                  xcodebuild -version
                  ls -nt /Applications/ | grep "Xcode*"
                  sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
                  xcodebuild -version
            - name: Install danger-js
              run: brew install danger/tap/danger-js

            - run: swift build

            - run: swift run danger-swift ci --verbose --failOnErrors
              if: ${{ github.event_name == 'pull_request' }}
              env:
                  DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
