name: CI

on:
    pull_request:

jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3.0.5

            # - name: Install danger-js
            #   run: brew install danger/tap/danger-js

            # - name: Install danger-swift
            #   run: brew install danger/tap/danger-swift

            - name: Cache RubyGems
              uses: actions/cache@v2
              with:
                  path: vendor/bundle
                  key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-gems-
            - name: Install SwiftLint
              run: |
                  curl -OL "https://github.com/realm/SwiftLint/releases/download/0.43.1/swiftlint_linux.zip"
                  unzip swiftlint_linux.zip
                  chmod +x swiftlint
                  sudo mv swiftlint /usr/local/bin/
            - name: Bundle install
              run: |
                  bundle config path vendor/bundle
                  bundle install --jobs 4 --retry 3
            - name: Run Danger
              run: danger-swift ci
              env:
                  DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
