name: CI

on:
    pull_request:

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: macos-latest

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Install danger-js
              run: brew install danger/tap/danger-js

            - name: Install danger-swift
              run: brew install danger/tap/danger-swift

            - name: Danger
              run: danger-swift ci
              env:
                  DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
