name: CI

on:
    pull_request:
        types: [opened, reopened, edited, synchronize]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Danger
              uses: danger/swift@3.18.0
              with:
                  args: --failOnErrors --no-publish-check
              env:
                  DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
