name: Run Danger

on: [pull_request]

jobs:
  danger:
    runs-on: macOS-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run Danger
      run: danger-swift ci
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}